CREATE TABLE IF NOT EXISTS "transaction_status" (
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
"name" TEXT NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `transactions` (
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`amount` INT NOT NULL,
`currency` TEXT NOT NULL,
`last_four` TEXT NOT NULL,
`expiry_month` INT NOT NULL,
`expiry_year` INT NOT NULL,
`paymen_intent` TEXT NOT NULL,
`paymen_method` TEXT NOT NULL,
`bank_return_code` TEXT NOT NULL,
`transaction_status_id` INT NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `customers` (
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`first_name` TEXT NOT NULL,
`last_name` TEXT NOT NULL,
`email` TEXT NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `orders` (
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`transaction_id` INT NOT NULL,
`customer_id` INT NOT NULL,
`status_id` INT NOT NULL,
`is_recurring` BOOLEAN NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);